#### 1. Import NumPy

Make sure to follow the conventions!

In [3]:
import numpy as np

#### 2. Create an array of 10 zeros 

In [4]:
np_zeros = np.zeros(10)

In [5]:
np_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create an array of 10 ones

In [6]:
np_ones = np.ones(10)

In [7]:
np_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [8]:
np_fives = np.full((10,), 5)

In [9]:
np_fives

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### 5. Create a vector, named `arr`, of 10 zeros the fifth value of which is 1.

In [10]:
arr = np.zeros(10)
arr[4] = 1

In [11]:
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6. Create an array of the integers from 10 to 50

In [12]:
ten_to_fifty_arr = np.linspace(10, 50, 41).astype(int)

In [13]:
ten_to_fifty_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 7. Reverse an array in **TWO** ways: using 'the Python way' and using a NumPy function

In [14]:
arr = np.array([1, 2, 3])

python_arr = arr.copy()

for i in range(int(len(python_arr) / 2)):
    tmp = python_arr[i]
    python_arr[i] = python_arr[len(python_arr) - 1 - i]
    python_arr[len(python_arr) - 1 - i] = tmp

python_arr


array([3, 2, 1])

In [15]:
np_arr = arr.copy()
np_arr = np_arr[::-1]

np_arr

array([3, 2, 1])

#### 8. Create a 5x5 array with 1 on the border and 0 inside

In [16]:
np_5darr = np.zeros((5,5))
np_5darr[[0, -1], :] = 1
np_5darr[:, [0, -1]] = 1

In [17]:
# Expected output
np_5darr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 9. Add a border filled with 0's on the two sides of an array.

> Hint: [np.pad](https://numpy.org/doc/stable/reference/generated/numpy.pad.html)

In [18]:
arr = np.array([1, 2, 3])

arr = np.pad(arr, (1,1), mode = "constant", constant_values = (0))

In [19]:
arr

array([0, 1, 2, 3, 0])

#### 10. Create an array of all the even integers from 10 to 50

In [20]:
ten_to_fifty_even_arr = np.linspace(10, 50, 21).astype(int)

In [21]:
ten_to_fifty_even_arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 11. Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
arr = np.linspace(0, 8, 9).astype(int)
arr = arr.reshape((3, 3))

In [23]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 12. Create a 3x3 identity matrix

In [24]:
arr = np.zeros((3, 3)).astype(int)
np.fill_diagonal(arr, 1)

In [25]:
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 13. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

> Hint: [np.diag](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)

In [26]:
arr = np.zeros((5, 5))
# TODO

In [27]:
# Expected output

#### 14. Use NumPy to generate a random number between 0 and 1

**Note**: Your result's value should be different from the one shown below.

In [28]:
random_number = np.random.random()

In [29]:
random_number

0.459350902347081

#### 15. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

**Note**: Your result's values should be different from the ones shown below.

In [30]:
random_normal_array = np.random.normal(size = 25)

In [31]:
random_normal_array

array([-0.99158965, -0.52092302,  0.35383656,  1.15749567, -0.57920613,
       -1.12208578, -1.06587798, -1.09740058,  0.91205099, -0.55771881,
       -0.76043187, -0.83461843,  1.02006013,  1.25471957, -0.07583777,
        0.50247852,  0.48122051, -0.53295318,  1.27111744,  0.72903252,
       -0.00643825,  0.30321258, -0.38116606,  0.92227864, -0.18995675])

#### 16. Create a 3x3x3 array with random values drawn from the uniform distribution

**Note**: Your result's values should be different from the ones shown below.


In [32]:
uniform_random_array = np.random.uniform(size = (3, 3, 3))

In [33]:
uniform_random_array

array([[[0.29645215, 0.72772205, 0.19360862],
        [0.22549433, 0.61950494, 0.3935779 ],
        [0.59825465, 0.29102139, 0.59003546]],

       [[0.82492319, 0.30615932, 0.99272864],
        [0.41008525, 0.46292799, 0.04708488],
        [0.68896221, 0.91194189, 0.38520611]],

       [[0.10648181, 0.80266967, 0.72304386],
        [0.9713462 , 0.5224374 , 0.91213029],
        [0.520526  , 0.73326671, 0.67914894]]])

#### 17. Create a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values.

**Note**: Your result's values should be different from the ones shown below.

In [34]:
uniform_matrix = np.random.uniform(size = (10, 10))


In [35]:
print("The array: ", uniform_matrix)
print("Min value: ", uniform_matrix.min())
print("Max value: ", uniform_matrix.max())

The array:  [[0.78843976 0.03994215 0.80820058 0.86073958 0.06491764 0.51739864
  0.54843776 0.71072358 0.81989327 0.93646222]
 [0.82166667 0.9536179  0.74699505 0.35417719 0.92271661 0.5676974
  0.43222012 0.16325938 0.98258839 0.62960321]
 [0.25456848 0.78118193 0.90661877 0.50838652 0.3853977  0.90869678
  0.60921929 0.00400728 0.18443205 0.90506044]
 [0.70746172 0.60065325 0.15684363 0.16179555 0.14860099 0.20742323
  0.72844942 0.39048775 0.2885248  0.18437001]
 [0.2594951  0.24263486 0.09612102 0.90494418 0.41421626 0.08634955
  0.05016936 0.38090458 0.23462342 0.36053519]
 [0.57066235 0.32647196 0.10910318 0.07426926 0.41378997 0.77036326
  0.91788959 0.31882449 0.08105472 0.42004694]
 [0.1267314  0.76816283 0.90108119 0.93408017 0.3806218  0.16274901
  0.4260279  0.00624572 0.32910561 0.15849836]
 [0.6993464  0.25075002 0.76887772 0.29326145 0.03155375 0.12343601
  0.4800577  0.20009005 0.17368873 0.75419439]
 [0.02294491 0.73719812 0.81510073 0.8556828  0.18020342 0.22317232
 

#### 18. Create a random array with values drawn from the uniform distribution of size 30 and find the mean value

In [36]:
random_arr = np.random.uniform(size = 30)

In [37]:
np.mean(random_arr)

0.5066528829587702

#### 19. Create the following matrix:

In [38]:
supposed_matrix = np.linspace(0.01, 1, 100)
supposed_matrix = supposed_matrix.reshape((10, 10))

In [39]:
supposed_matrix

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 20. Create an array of 20 linearly spaced points between 0 and 1:

In [40]:
arr = np.linspace(0, 1, 20)

In [41]:
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs.

In all of the solutions until the last task before the section `NumPy Operations` you should be using `mat`.

In [42]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 21. Write code that reproduces the output shown below.

In [43]:
mat[2:, 1:]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 22. Write code that reproduces the output shown below.

In [44]:
mat[3, 4]

20

#### 23. Write code that reproduces the output shown below.

In [45]:
mat[0:3, 1].reshape((3, 1))

array([[ 2],
       [ 7],
       [12]])

In [46]:
# Expected output

#### 24. Write code that reproduces the output shown below.

In [47]:
mat[-1]

array([21, 22, 23, 24, 25])

#### 25. Write code that reproduces the output shown below.

In [48]:
mat[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 26. Find the indices of the non-zero elements in the provided array.

In [60]:
arr = np.array([1,2,0,0,4,0])

arr[arr != 0]

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [1, 1, 1, 1]]],


       [[[0, 1, 2, 3],
         [0, 1, 2, 3]]]])

In [50]:
# Expected output

## NumPy Operations

#### 27. Get the sum of all the values in mat

In [51]:
# Expected output

#### 28. Get the standard deviation of the values in mat

In [52]:
# Expected output

#### 29. Get the sum of all the columns in mat

In [53]:
# Expected output

#### 30. Create and multiply a 5x3 matrix by a 3x2 matrix (matrix product). The matrices can hold random values or you can create them manually.

**Note**: In this example output the matrices held random values, so your result's values should be different from the ones shown below.

In [54]:
# Expected output

#### 31. Create a 1D array of random integers between 0 and 9. Negate all elements which are between 3 and 8.

In [55]:
# Expected output

#### 32. Create a random array of size 10 and sort it

In [56]:
# Expected output

#### 33. Create random vector of values drawn from the uniform distribution of size 10 and replace the maximum value by 0

In [57]:
# Expected output

#### 34. What function can we use to ensure that we always get the same random numbers?

> **Your answer**: ...write here...